# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f390867bf122b6b77e9779cb5018a984a47b44cdb42a27abc68024fc324507e80a440439d109c930c18fbb8050ec6c02072160eec4df3a3ff92b7671ed6875a

test:
  secret_key_base: 6cb814eadd6a70ba4e45958a375e4815ed4c92b0317b97052fd905a58a84f6b446b167106e1811ff785e2b437d1ee8f9981ff378fef5d35887f61ee2bf3915bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
